package project.model;
// Generated 06-feb-2021 12:39:09 by Hibernate Tools 4.3.1



/**
 * Cotanieve generated by hbm2java
 */
public class Cotanieve  implements java.io.Serializable {


     private Integer idCotaNieve;
     private Dia dia;
     private String periodo;

    public Cotanieve() {
    }

    public Cotanieve(Dia dia, String periodo) {
       this.dia = dia;
       this.periodo = periodo;
    }
   
    public Integer getIdCotaNieve() {
        return this.idCotaNieve;
    }
    
    public void setIdCotaNieve(Integer idCotaNieve) {
        this.idCotaNieve = idCotaNieve;
    }
    public Dia getDia() {
        return this.dia;
    }
    
    public void setDia(Dia dia) {
        this.dia = dia;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


